insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TANCREDO NEVES GABINETE 56');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA AFONSO ARINOS GABINETE 08');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA NILO COELHO 1º PAVIMENTO GABINETE 10');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA AFONSO ARINOS GABINETE 03');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TANCREDO NEVES GABINETE 51');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 19');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 23');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 10');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','10º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','3º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 05');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 13');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','16º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA AFONSO ARINOS GABINETE 10');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','12º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 21');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','5º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA RUY CARNEIRO GABINETE 04');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 06');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA NILO COELHO PAVIMENTO TÉRREO SALA 2');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA AFONSO ARINOS GABINETE 06');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL EDIFÍCIO PRINCIPAL   ','ALA DINARTE MARIZ GABINETE 04');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','13º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 04');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','17º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA RUY CARNEIRO GABINETE 01');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','21º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','11º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','2º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','23º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','4º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA AFONSO ARINOS GABINETE 09');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 03');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 16');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TANCREDO NEVES GABINETE 50');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','7º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL EDIFÍCIO PRINCIPAL  ','ALA DINARTE MARIZ GABINETE 02');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 15');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','6º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA ALEXANDRE COSTA SUBSOLO  GABINETE 03');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 11');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA AFONSO ARINOS GABINETE 02');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA AFONSO ARINOS GABINETE 05');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA ALEXANDRE COSTA 1º PAVIMENTO GABINETE 21');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 14');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 07');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL EDIFÍCIO PRINCIPAL  ','1º ANDAR  GABINETE 05');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA AFONSO ARINOS GABINETE 01');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA AFONSO ARINOS GABINETE 12');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','18º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 02');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA NILO COELHO PAVIMENTO TÉRREO GABINETE 08');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA RUY CARNEIRO GABINETE 02');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','24º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA FILINTO MÜLLER GABINETE 01');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 25');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 09');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','22º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 08');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','TÉRREO ALA ALEXANDRE COSTA 1º PAVIMENTO GABINETE 01');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','9º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 17');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','15º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','25º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA AFONSO ARINOS GABINETE 07');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 24');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 12');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA NILO COELHO PAVIMENTO TÉRREO GABINETE 11');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 01');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TANCREDO NEVES GABINETE 54');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA AFONSO ARINOS GABINETE 11');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL EDIFÍCIO PRINCIPAL   ','ALA DINARTE MARIZ GABINETE 01');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA AFONSO ARINOS GABINETE 04');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','14º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA RUY CARNEIRO GABINETE 03');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA AFONSO ARINOS GABINETE 13');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','20º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','19º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TANCREDO NEVES GABINETE 57');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 1','8º PAVIMENTO');
insert into Localizacao (endereco, complemento) values ('SENADO FEDERAL ANEXO 2','ALA TEOTÔNIO VILELA GABINETE 18');
