-- INSERTS SENADOR
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ACIR GURGACZ','PDT','RO','Titular','2015 / 2023','25/02/1962','sen.acirgurgacz@senado.leg.br','PBB5186');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ALESSANDRO VIEIRA','CIDADANIA','SE','Titular','2019 / 2027','03/04/1975','sen.alessandrovieira@senado.leg.br',NULL);
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ALVARO DIAS','PODEMOS','PR','Titular','2015 / 2023','07/12/1944','sen.alvarodias@senado.leg.br','PBA6476');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ANGELO CORONEL','PSD','BA','Titular','2019 / 2027','03/05/1958','sen.angelocoronel@senado.leg.br','PBB9991');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ANTONIO ANASTASIA','PSDB','MG','Titular','2015 / 2023','09/05/1961','sen.antonioanastasia@senado.leg.br','PBB7630');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('AROLDE DE OLIVEIRA','PSD','RJ','Titular','2019 / 2027','11/03/1937','sen.aroldedeoliveira@senado.leg.br','PBB8782');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('CARLOS VIANA','PSD','MG','Titular','2019 / 2027','22/03/1963','sen.carlosviana@senado.leg.br',NULL);
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('CHICO RODRIGUES','DEM','RR','Titular','2019 / 2027','23/04/1951','sen.chicorodrigues@senado.leg.br','PBC0008');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('CID GOMES','PDT','CE','Titular','2019 / 2027','27/04/1963','sen.cidgomes@senado.leg.br','PBA6482');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('CIRO NOGUEIRA','PP','PI','Titular','2019 / 2027','21/11/1968','sen.cironogueira@senado.leg.br','PBB5174');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('CONFUCIO MOURA','MDB','RO','Titular','2019 / 2027','16/05/1948','sen.confuciomoura@senado.leg.br',NULL);
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('DANIELLA RIBEIRO','PP','PB','Titular','2019 / 2027','26/03/1972','sen.daniellaribeiro@senado.leg.br','PBB9997');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('DARIO BERGER','MDB','SC','Titular','2015 / 2023','07/12/1956','sen.darioberger@senado.leg.br','PBB5170');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('DAVI ACOLUMBRE','DEM','AP','Titular','2015 / 2023','19/06/1977','sen.davialcolumbre@senado.leg.br','PBB8781');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('EDUARDO BRAGA','MDB','AM','Titular','2019 / 2027','06/12/1960','sen.eduardobraga@senado.leg.br','PBB5159');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('EDUARDO GIRÃO','PODEMOS','CE','Titular','2019 / 2027','25/09/1972','sen.eduardogirao@senado.leg.br',NULL);
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('EDUARDO GOMES','MDB','TO','Titular','2019 / 2027','28/04/1966','sen.eduardogomes@senado.leg.br','PBC0009');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ELIZIANE GAMA','CIDADANIA','MA','Titular','2019 / 2027','27/02/1977','sen.elizianegama@senado.leg.br','PBA6470');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ELMANO FERRER','PODEMOS','PI','Titular','2015 / 2023','01/08/1942','sen.elmanoferrer@senado.leg.br','PBA6469');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ESPERIDIÃO AMIN','PP','SC','Titular','2019 / 2027','21/12/1947','sen.esperidiaoamin@senado.leg.br','PBA6467');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('FABIANO CONTARATO','REDE','ES','Titular','2019 / 2027','20/06/1966','sen.fabianocontarato@senado.leg.br','PBB8794');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('FERNANDO BEZERRA','MDB','PE','Titular','2015 / 2023','07/12/1957','sen.fernandobezerracoelho@senado.leg.br','PBA6478');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('FERNANDO COLLOR','PROS','AL','Titular','2015 / 2023','12/08/1949','Sen.fernandocollor@senado.leg.br','PBB5181');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('FLÁVIO ARNS','REDE','PR','Titular','2019 / 2027','09/11/1950','sen.flavioarns@senado.leg.br','PBB5156');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('FLÁVIO BOLSONARO','PSL','RJ','Titular','2019 / 2027','30/04/1981','sen.flaviobolsonaro@senado.leg.br','PBB5180');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('HUMBERTO COSTA','PT','PE','Titular','2019 / 2027','07/07/1957','sen.humbertocosta@senado.leg.br','PBA6473');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('IRAJÁ ABREU','PSD','TO','Titular','2019 / 2027','03/02/1983','sen.iraja@senado.leg.br','PBB9994');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('IZALCI LUCAS','PSDB','DF','Titular','2019 / 2027','07/04/1956','sen.izalcilucas@senado.leg.br','PBB8793');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('JADER BARBALHO','MDB','PA','Titular','2019 / 2027','27/10/1944','sen.jaderbarbalho@senado.leg.br',NULL);
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('JAQUES WAGNER','PT','BA','Titular','2019 / 2027','16/03/1951','sen.jaqueswagner@senado.leg.br','PBA6479');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('JARBAS VASCONCELOS','MDB','PE','Titular','2019 / 2027','23/08/1942','sen.jarbasvasconcelos@senado.leg.br','PBB8791');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('JAYME CAMPOS','DEM','MT','Titular','2019 / 2027','13/09/1951','Sen.JaymeCampos@senado.leg.br','PBB5177');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('JEAN PAUL PRATES','PT','RN','1º Suplente','2015 / 2023','19/06/1968','sen.jeanpaulprates@senado.leg.br','PBB5168');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('JORGE KAJURU','CIDADANIA','GO','Titular','2019 / 2027','20/01/1961','sen.jorgekajuru@senado.leg.br',NULL);
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('JORGINHO MELLO','PL','SC','Titular','2019 / 2027','15/07/1956','sen.jorginhomello@senado.leg.br','PBB5179');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('JOSÉ MARANHÃO','MDB','PB','Titular','2015 / 2023','06/09/1933','sen.josemaranhao@senado.leg.br','PBB8783');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('JOSÉ SERRA','PSDB','SP','Titular','2015 / 2023','19/03/1942','sen.joseserra@senado.leg.br','PBC0011');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('SELMA ARRUDA','PODEMOS','MT','Titular','2019 / 2027','20/01/1963','sen.selmaarruda@senado.leg.br','PBB5160');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('KÁTIA ABREU','PDT','TO','Titular','2015 / 2023','02/02/1962','sen.katiaabreu@senado.leg.br','PBB5173');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('LASIER MARTINS','PODEMOS','RS','Titular','2015 / 2023','14/04/1942','sen.lasiermartins@senado.leg.br','PBB5176');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('LEILA BARROS','PSB','DF','Titular','2019 / 2027','30/09/1971','sen.leilabarros@senado.leg.br','PBB8784');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('LUCAS BARRETO','PSD','AP','Titular','2019 / 2027','10/11/1964','sen.lucasbarreto@senado.leg.br','PBB5185');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('LUIZ CARLOS HEINZE','PP','RS','Titular','2019 / 2027','14/09/1950','sen.luiscarlosheinze@senado.leg.br','PBB9990');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('LUIZ CARLOS DO CARMO','MDB','GO','1º Suplente','2015 / 2023','02/04/1958','sen.luizcarlosdocarmo@senado.leg.br','PBB9987');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('MAILZA GOMES','PP','AC','1º Suplente','2015 / 2023','10/12/1976','sen.mailzagomes@senado.leg.br','PBB5182');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('MAJOR OLÍMPIO','PSL','SP','Titular','2019 / 2027','20/03/1962','sen.majorolimpio@senado.leg.br','PBA6468');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('MARA GABRILLI','PSDB','SP','Titular','2019 / 2027','28/09/1967','sen.maragabrilli@senado.leg.br',NULL);
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('MARCELO CASTRO','MDB','PI','Titular','2019 / 2027','09/06/1950','sen.marcelocastro@senado.leg.br','PBB5161');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('MÁRCIO BITTAR','MDB','AC','Titular','2019 / 2027','28/06/1963','sen.marciobittar@senado.leg.br','PBB8786');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('MARCOS DO VAL','PODEMOS','ES','Titular','2019 / 2027','15/06/1971','sen.marcosdoval@senado.leg.br','PBB8789');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('MARCOS ROGÉRIO','DEM','RO','Titular','2019 / 2027','07/07/1978','sen.marcosrogerio@senado.leg.br','PBB9998');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('MARIA DO CARMO ALVES','DEM','SE','Titular','2015 / 2023','23/08/1941','sen.mariadocarmoalves@senado.leg.br','PBC0014');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('MECIAS JESUS','REPUBLICANOS','RR','Titular','2019 / 2027','08/02/1962','sen.meciasdejesus@senado.leg.br','PBB5166');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('NELSON TRAD','PSD','MS','Titular','2019 / 2027','05/09/1961','sen.nelsinhotrad@senado.leg.br','PBB5164');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('OMAR AZIZ','PSD','AM','Titular','2015 / 2023','13/08/1958','sen.omaraziz@senado.leg.br','PBB5184');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ORIOVISTO GUIMARÃES','PODEMOS','PR','Titular','2019 / 2027','12/08/1945','sen.oriovistoguimaraes@senado.leg.br','PBC0004');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('OTTO ALENCAR','PSD','BA','Titular','2015 / 2023','28/08/1947','sen.ottoalencar@senado.leg.br','PBB5171');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('PAULO PAIM','PT','RS','Titular','2019 / 2027','15/03/1950','sen.paulopaim@senado.leg.br','PBB5163');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('PAULO ROCHA','PT','PA','Titular','2015 / 2023','01/04/1951','sen.paulorocha@senado.leg.br','PBB8792');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('PLÍNIO VALÉRIO','PSDB','AM','Titular','2019 / 2027','30/01/1955','sen.pliniovalerio@senado.leg.br','PBA6483');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('RANDOLFE RODRIGUES','REDE','AP','Titular','2019 / 2027','06/11/1972','sen.randolferodrigues@senado.leg.br','PBA6475');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('REGUFFE','PODEMOS','DF','Titular','2015 / 2023','05/09/1972','sen.reguffe@senado.leg.br',NULL);
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('RENAN CALHEIROS','MDB','AL','Titular','2019 / 2027','16/09/1955','sen.renancalheiros@senado.leg.br','PBB5187');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ROBERTO ROCHA','PSDB','MA','Titular','2015 / 2023','04/08/1965','sen.robertorocha@senado.leg.br','PBA6472');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('RODRIGO CUNHA','PSDB','AL','Titular','2019 / 2027','11/05/1981','sen.rodrigocunha@senado.leg.br','PBB5169');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('RODRIGO PACHECO','DEM','MG','Titular','2019 / 2027','03/11/1976','sen.rodrigopacheco@senado.leg.br','PBB5157');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ROGÉRIO CARVALHO','PT','SE','Titular','2019 / 2027','02/08/1968','sen.rogeriocarvalho@senado.leg.br','PBB9989');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ROMARIO','PODEMOS','RJ','Titular','2015 / 2023','29/01/1966','sen.romario@senado.leg.br','PBC0006');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ROSE DE FREITAS','PODEMOS','ES','Titular','2015 / 2023','23/01/1949','rose.freitas@senadora.leg.br','PBB8785');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('SÉRGIO PETECÃO','PSD','AC','Titular','2019 / 2027','20/04/1960','sergio.petecao@senador.leg.br','PBA6474');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('SIMONE TEBET','MDB','MS','Titular','2015 / 2023','22/02/1970','sen.simonetebet@senado.leg.br','PBB9996');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('SORAYA THRONICKE','PSL','MS','Titular','2019 / 2027','01/06/1973','sen.sorayathronicke@senado.leg.br','PBA6481');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('STYVENSON VALENTM','PODEMOS','RN','Titular','2019 / 2027','07/02/1977','sen.styvensonvalentim@senado.leg.br','PBB5165');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('TASSO JEREISSATI','PSDB','CE','Titular','2015 / 2023','15/12/1948','sen.tassojereissati@senado.leg.br','PBC0013');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('TEOMÁRIO MOTA','PROS','RR','Titular','2015 / 2023','15/02/1958','sen.telmariomota@senado.leg.br','PBB5183');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('VANDERLAN CARDOSO','PP','GO','Titular','2019 / 2027','15/11/1962','sen.vanderlancardoso@senado.leg.br',NULL);
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('VENEZIANO VITAL DO RÊGO','PSB','PB','Titular','2019 / 2027','17/07/1970','sen.venezianovitaldorego@senado.leg.br','PBB5188');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('WELLINGTON FAGUNDES','PL','MT','Titular','2015 / 2023','01/06/1957','sen.wellingtonfagundes@senado.leg.br','PBB8788');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('WEVERTON DE SOUSA','PDT','MA','Titular','2019 / 2027','08/10/1979','sen.wevertonrocha@senado.leg.br','PBB5172');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ZENAIDE MAIA','PROS','RN','Titular','2019 / 2027','27/11/1954','sen.zenaidemaia@senado.leg.br','PBB5162');
INSERT INTO Senador (Nome,Partido,UF,Titularidade,Mandato,DtNasc,Email,fk_Placa) values  ('ZEQUINHA MARINHO','PSC','PA','Titular','2019 / 2027','18/09/1959','sen.zequinhamarinho@senado.leg.br','PBB9993');
